### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by devlfm** [ptdede/nativescript-image-caching#2]
Hi,

I need to set rotation while loading.. I saw that was possible to apply transformation https://futurestud.io/tutorials/glide-how-to-rotate-images but nativescript says to me that override method is final and I don't know how to do it..

Can you help me?

Thank you

**Comment by ptdede** [comment]
Hi @devlfm .. Thanks for interest on this plugin. But we are not longer maintain this plugin. As this is only EXPERIMENTAL plugin. 

Please use Nativescript core module [ImageCache]( https://docs.nativescript.org/ui/ns-ui-widgets/image-cache) or [nativescript-image-cache-it](https://github.com/triniwiz/nativescript-image-cache-it) that used picasso instead.

**Comment by devlfm** [comment]
:( I understand.. thank you

**Comment by ptdede** [comment]
@devlfm thanks!
